"""empty message

Revision ID: 6ba7503c65eb
Revises: 127c4a5c903f
Create Date: 2021-07-20 09:19:26.595603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba7503c65eb'
down_revision = '127c4a5c903f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_blog',
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_blog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_blog'], ['category.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_category'], ['blog.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_blog')
    # ### end Alembic commands ###
