"""empty message

Revision ID: d10d9f189681
Revises: 6ba7503c65eb
Create Date: 2021-07-21 15:51:39.926835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10d9f189681'
down_revision = '6ba7503c65eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('slung', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slung')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('slung', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slung')
    )
    op.create_table('category_blog',
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_blog', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_blog'], ['category.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['id_category'], ['blog.id'], ondelete='cascade')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('category_blog')
    op.drop_table('category')
    op.drop_table('blog')
    # ### end Alembic commands ###
